### ISSUE TITLE
[Bug] Storm Wing and Flashing unbind A as Moving Left

### ISSUE THREAD

**Issue by Hunyol** [LambdaInnovation/AcademyCraft#712]
**Describe the bug**
Using Storm Wing seems to cause A to unbind if its as Strafe Left *and has a conflicting keybind*, not if anything else is Strafe Left or A is anything else
**To Reproduce**
1. Have A as Strafe Left *and something else*
2. Activate Storm Wing
3. Use one of the speed boosts
4. Try and strafe left

**Expected behavior**
Should be able to move normally

**Desktop (please complete the following information):**
 - OS: Windows
 - MC Version and Forge version: MC 1.12.2 Forge 14.23.5.2796
 - Version 1.1.0 beta4

**Comment by nirvanaxiao6** [comment]
Duplicated with #651 
And we cannot reproduce the bug.

**Comment by Hunyol** [comment]
I should also include, in the controls it does not appear to be unbound

**Comment by fireair** [comment]
I get this bug as well

**Comment by Hunyol** [comment]
Breakthrough: It only happens when theres a conflicting keybind

**Comment by Ruchian** [comment]
So I created a mini modpack to test this.
Minecraft version 1.12.2
Forge version 14.23.5.2815

It contains the following mods:
AcademyCraft-1.1.0
Just Enough Items 1.12.2-4.14.267
LambdaLib2-0.1.7

I can diffidently recreate this bug with just these mods.

Just Enough Items has a key called "Add/Remove Bookmarked Ingredients"
This key is set on "A" by default and doesn't show up as a keybind conflict, because it is only used when the inventory is opened.

I used cheats to give myself Vector Manip, Level 5, Learn_All. I put Storm Wing on 1. (Mouse Button 0)
I fly around a bit, cancel the skill and A stops doing anything. You cannot move left.

In the Options > Controls menu, A is still bound to Strafe Left. (It is not actually unbind)
But unbinding the key and rebinding A to Strafe Left will allow you to walk left again.

**Comment by nirvanaxiao6** [comment]
You did a really good job. It does help us a lot. Thanks for you help.

 For the problem, you can wait for weathfold to find out why it happens. 

Really appreciate you a lot for your feedback.

**Comment by Keltas** [comment]
I wanted to add that I get this bug also with the Flashing teleporter skill.

**Comment by WeAthFoLD** [comment]
Fixed.

**Comment by nirvanaxiao6** [comment]
NOT fixed in AcademyCraft 1.1.2 -190427

**Comment by WeAthFoLD** [comment]
@nirvanaxiao6 Please check again

**Comment by Hax02** [comment]
Still getting this bug as of 1.1.2

**Comment by DarianLStephens** [comment]
I'm also getting this bug in 1.1.2, just to confirm it's still a problem.
Just for testing, I changed the troublesome JEI hotkey to instead be D, and I was still able to move right after using the Flashing ability, so it seems to be something with left specifically.

**Comment by Minephliss** [comment]
This bug is still exist in 1.1.3. After using Flashing it occured

**Comment by Renniuq** [comment]
It might be worth noting this issue happens with **any** of the movement keys, provided there is a conflicting keybind. For instance, Valkyrien Skies adds control bindings for an airship using the WASD keys, and with that installed, using Flashing or Storm Wing will lock out all 4 keys, unless you rebind the Valkyrien Skies controls to something else, like the arrow keys. Thought it'd be worth noting it wasn't limited to the A key in particular.
